dir = "../random-stuff"


[[languages]]
name = "Rust"
extensions = ["rs"]
[languages.comments]
line = ["//", "///", "//!"]
[languages.comments.block]
open = "/*"
close = "*/"


[[languages]]
name = "C"
extensions = ["c", "h"]
[languages.comments]
line = ["//"]
[languages.comments.block]
open = "/*"
close = "*/"


[[languages]]
name = "Python"
extensions = ["py"]
[languages.comments]
line = ["#"]
# [languages.comments.block]
# open = ""
# close = ""


[[languages]]
name = "Lua"
extensions = ["lua"]
[languages.comments]
line = ["--"]
[languages.comments.block]
open = "--[["
close = "]]"


[[languages]]
name = "Haskell"
extensions = ["hs"]
[languages.comments]
line = ["--"]
[languages.comments.block]
open = "{-"
close = "-}"
